# translational 
kp_x: 0.05
kp_y: 0.05
kp_z: 30.0
#-----
ki_x: 0.
ki_y: 0.
ki_z: 10.0
#-----
kd_x: 0.
kd_y: 0.
kd_z: 30.0
#-----

# rotational 
kp_phi: 0.1
kp_theta: 0.1
kp_psi: 0.0005
#-----
ki_phi: 0.
ki_theta: 0.
ki_psi: 0.
#-----
kd_p: 0.001
kd_q: 0.001
kd_r: 0.00005